name: SQL backend unit tests

on:
  push:


jobs:
  run_unittests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
        with:
        node-version: '12.x'
      - name: Install dependencies
        run: |
          cd SQL_Server
          npm ci
      - name: Run all unittests
        run: |
          cd SQL_Server
          npm test
