name: SQL backend unit tests

on:
  push:


env:
  DB_USER: root
  DB_PASSWORD: root
  MATCHA_DB: sekesidb
  MATCHA_TEST_DB: sekesitest
  TEST: 'true'
  APIkey: ${{ secrets.API_KEY}},
  APIurl: ${{ secrets.API_URL}},
  SIGNATURE: ${{ secrets.SIGNATURE}},

jobs:
  run_unittests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          echo "LOLOL"
          mysql --version
          sudo systemctl status mysql.service

          sudo mysql -e 'CREATE DATABASE ${{ env.MATCHA_DB }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          sudo mysql -e 'CREATE DATABASE ${{ env.MATCHA_TEST_DB }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

          sudo mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.MATCHA_DB }} < server/sql_scripts/define_db.sql
          sudo mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.MATCHA_TEST_DB }} < server/sql_scripts/define_db.sql

          sudo mysql -e "CREATE USER 'sammy'@'localhost' IDENTIFIED BY 'password';" -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
          sudo mysql -e "GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'sammy'@'localhost' WITH GRANT OPTION;"  -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Install dependencies
        run: |
          cd server
          npm ci
      - name: Run all unittests
        run: |
          cd server
          npm test
      - name: SQL users table
        run: |
          sudo mysql -e 'use sekesitest; select * from USERS;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

