name: SQL backend unit tests

on:
  push:

jobs:
  run_unittests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
      - name: Install dependencies
        run: |
          cd SQL_Server
          npm ci
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE sekesidb;' -u sammy -p ${{ secrets.DatabasePassword }}
      - name: Run all unittests
        run: |
          cd SQL_Server
          npm test
